apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - clustermanagers
  - kubernetesclusters
  - virtualkubernetesclusters
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - unikorn-cloud.org
  resources:
  - clustermanagerapplicationbundles
  - kubernetesclusterapplicationbundles
  - virtualkubernetesclusterapplicationbundles
  verbs:
  - list
  - watch
# Find project namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
