apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-server
  template:
    metadata:
      labels:
        app: unikorn-server
    spec:
      containers:
      - name: unikorn-server
        image: {{ include "unikorn.serverImage" . }}
        args:
        - --namespace={{ .Release.Namespace }}
        {{- with $cors := .Values.cors -}}
          {{- range $origin := $cors.allowOrigin }}
            {{ printf "- --cors-allow-origin=%s" $origin | nindent 8 }}
          {{- end }}
          {{- if $cors.maxAge }}
            {{ printf "- --cors-max-age=%s" $cors.maxAge | nindent 8 }}
          {{- end }}
        {{- end }}
        - --identity-host=https://{{ include "unikorn.identity.host" .}}
        {{- with $caSecretNamespace := ( include "unikorn.identity.ca.secretNamespace" . ) -}}
          {{ printf "- --identity-ca-secret-namespace=%s" $caSecretNamespace | nindent 8 }}
        {{- end }}
        {{- with $caSecretName := ( include "unikorn.identity.ca.secretName" . ) -}}
          {{ printf "- --identity-ca-secret-name=%s" $caSecretName | nindent 8 }}
        {{- end }}
        - --region-host=https://{{ include "unikorn.region.host" . }}
        {{- with $caSecretNamespace := ( include "unikorn.region.ca.secretNamespace" . ) -}}
          {{ printf "- --region-ca-secret-namespace=%s" $caSecretNamespace | nindent 8 }}
        {{- end }}
        {{- with $caSecretName := ( include "unikorn.region.ca.secretName" . ) -}}
          {{ printf "- --region-ca-secret-name=%s" $caSecretName | nindent 8 }}
        {{- end }}
        {{- if .Values.otlpEndpoint -}}
          {{ printf "- --otlp-endpoint=%s" .Values.otlpEndpoint | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 6080
        - name: prometheus
          containerPort: 8080
        - name: pprof
          containerPort: 6060
        # Note, this is quite CPU intensive, especially when going wide!
        # TODO: profile me.
        resources:
          requests:
            cpu: "1"
            memory: 50Mi
          limits:
            cpu: "2"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-server
      securityContext:
        runAsNonRoot: true
