apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-server
  template:
    metadata:
      labels:
        app: unikorn-server
    spec:
      containers:
      - name: unikorn-server
        image: {{ include "unikorn.serverImage" . }}
        args:
        - --namespace={{ .Release.Namespace }}
        {{- with $cors := .Values.server.cors }}
          {{- range $origin := $cors.allowOrigin }}
            {{ printf "- --cors-allow-origin=%s" $origin | nindent 8 }}
          {{- end }}
          {{- if $cors.maxAge }}
            {{ printf "- --cors-max-age=%s" $cors.maxAge | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- with $identity := .Values.server.identity }}
        - --identity-host={{ $identity.host }}
          {{- if $identity.caSecretNamespace }}
            {{ printf "- --identity-ca-secret-namespace=%s" $identity.caSecretNamespace | nindent 8 }}
          {{- end }}
          {{- if $identity.caSecretName }}
            {{ printf "- --identity-ca-secret-name=%s" $identity.caSecretName | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- with $region := .Values.server.region }}
          {{- if $region.host }}
            {{ printf "- --region-host=%s" $region.host | nindent 8 }}
          {{- end }}
          {{- if $region.caSecretNamespace }}
            {{ printf "- --region-ca-secret-namespace=%s" $region.caSecretNamespace | nindent 8 }}
          {{- end }}
          {{- if $region.caSecretName }}
            {{ printf "- --region-ca-secret-name=%s" $region.caSecretName | nindent 8 }}
          {{- end }}
        {{- end }}
        {{- if .Values.server.otlpEndpoint }}
          {{ printf "- --otlp-endpoint=%s" .Values.server.otlpEndpoint | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 6080
        - name: prometheus
          containerPort: 8080
        - name: pprof
          containerPort: 6060
        # Note, this is quite CPU intensive, especially when going wide!
        # TODO: profile me.
        resources:
          requests:
            cpu: "1"
            memory: 50Mi
          limits:
            cpu: "2"
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-server
      securityContext:
        runAsNonRoot: true
