apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unikorn-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
  annotations:
  {{- with $clusterIssuer := ( include "unikorn.ingress.clusterIssuer" . ) }}
    cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
  {{- end }} 
  {{- with $ingress := .Values.ingress }}
    {{- if $ingress.externalDns }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "unikorn.kubernetes.host" . }}
    {{- end }}
  {{- end }}
spec:
  {{- with $ingress := .Values.ingress }}
  {{- if $ingress.class }}
  ingressClassName: {{ $ingress.class }}
  {{- end }}
  {{- end }}
  # For development you will want to add these names to /etc/hosts for the ingress
  # endpoint address.
  tls:
  - hosts:
    - {{ include "unikorn.kubernetes.host" . }}
    secretName: unikorn-server-ingress-tls
  rules:
  - host: {{ include "unikorn.kubernetes.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unikorn-server
            port:
              name: http
