apiVersion: v1
kind: Service
metadata:
  name: unikorn-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
    {{- include "unikorn.prometheusLabels" (dict "job" "unikorn-server") | nindent 4 }}
spec:
  selector:
    app: unikorn-server
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: prometheus
    port: 8080
    targetPort: prometheus
