apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unikorn-kubernetes-client
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: unikorn-client-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: unikorn-kubernetes-client-certificate
  commonName: unikorn-kubernetes
