apiVersion: unikorn-cloud.org/v1alpha1
kind: ClusterManagerApplicationBundle
metadata:
  name: cluster-manager-1.0.0
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  version: 1.0.0
  applications:
  - name: vcluster
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "vcluster" }}
      version: 0.20.1
  - name: cert-manager
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "cert-manager" }}
      version: v1.14.5
  - name: cluster-api
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "cluster-api" }}
      version: v0.2.1
  - name: kamaji
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "kamaji" }}
      version: 1.0.0
  - name: kamaji-control-plane-provider
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "kamaji-control-plane-provider" }}
      version: v0.13.0
