// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/identity/pkg/openapi"
	externalRef2 "github.com/unikorn-cloud/region/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9CW8jt5LwXyH628W84JNkSZbtsYDFgzPezDNyjDFX9nuRP4PdXZL43E12SLY9iuH/",
	"vuDRN1u3J548IQHGdvOqg8WqYlXx0QtYnDAKVApv/OglmOMYJHD9WxClQgL/GVM8A351eZ19VR9DEAEn",
	"iSSMemPv4xyQbY5i0x5dXfa8jkfU5wTLudfxKI7BGzfG9Toeh99TwiH0xpKn0PFEMIcYq3n+g8PUG3v/",
	"56hY6ZH5Ko5qA4Xe01PHu0t94BQkiDfm88qF/5j3yGFYtfYdFt1cn1k34zNMyR9YLWzlksuN2xdbHXLr",
	"FaeU3DFOu0HE0vCWhEAlkYvb+0FvcNY7u03uZrcsAYoTciuA3wO/rUxswEs4+xcEciVktl07UPlAXxGe",
	"bE4DCofZOjQyzdoByYbZExxmOAvFyAWFnbAMxMdFAivAkIsEEJtm4DwAwhwQFneEztCU8Ry631Pgizp4",
	"aoKtAXStUa29CnjAOFiwBxWwAxbHjN5KPPsAEQSS8SWgXiABUsEp8UwgyVCMZTBHeIYJFRJxECzlAQhE",
	"KJJzUJDHaKKB/a97HKUw8ToTKuepQA9zoAhowEII0YKlaAYSTby/Szz7rylj/3l8GWA5Sfv94an6k4/5",
	"fx5fhmw28dpwKfHMKyONSIi1iFbE8caekJzQmffUyf6AOccLjat7wmWKox83loq241eWjq3LVVz7ZEYF",
	"Ib9nIQFzSHHAEt4wKjmLriNM4b1poj8yKoHqH3GSRCTQEunoX0JB+ejBFxwnEagfY5A4xFKvzwITwhSn",
	"kdRY3OY8+pUTCWbVVezaxaJErRZZiFBx9vYa2HvqWDgbeNkXsHbpioVEAoH6kouLsef3T879YzjtnmM4",
	"6Y6G/ln3fOSPutPRcOqf4VMfg9rl98CFAfF+0Bue9YZex3tg/C5iOLxmLBLe+LdHD6eSiQBHimPVYggl",
	"cRq/B71k4Y37Tx0vxsGcUL3YaYTvGdfLCM5OTl/DMOxOz7HfHZ0ch91zfIy7J4Pjs5Pp2evR8NTXuMuG",
	"On7qNKh5sz49G0d1K0kdm2Qjun5uYfsXRd4mKTenTY0aVWJtQJo2OdFKoc/t4mwtSmnZIxJGBTiU4/f2",
	"0/aE0nygTjuiETTsD4+7/bPu8eDjoD8enYxHJ//0Ot4ccCTnHySWqfDG9ld1UJBdaFBT18ZeODrt98NT",
	"6ML56Ul35I9GXfy6/7r7ejT1h1N8fHrWV3u7UIvGXoBhODgPz7qDvuKh0/6g+zoYBl2AM+ifnvrnxwGY",
	"LvdECQlCZzkY+R8h3Fravgccuuh+UbdLemoTVPuKbcj324F+bvrdbEdA4aZeRIRWy2pUFJqMDQGtdnfA",
	"6JTM1iApCyTIrpAccOyNH12zO6SFGT7legz3Kr5FaZCdEC+Mm4rzqmHsjz3/9cnJ8GQadEf9AHdHr4d+",
	"Fwf9sy4E+LXfH/j982DodZ5NkSkpKSERd+pfQf4Ab3yiVJiXpLe0C8cmg7tZ+tsUkQemfvlMfbM1V684",
	"MZqsbQ6NzbwHOAggkRCW+d/l6zEq5BwL5ANQlHVDmIbogUQR8gFN02hKokj9VSxoMOeMslREi96E/j+W",
	"ohgvUMKiSPsXMoeDHiBmlEjGEZECldlLfzQ7BAnNahMqGcIPmEikUBiB9hCyqR6TJVA6tjbDg49Da4xs",
	"d7oB54x7Y4/QexyR8NZizOuYL7dVnGb49Fm4QLaL1/EkxwHcakFwcuYHg1F47oej08G075/gs2Hovz7u",
	"D0bn/ukZ9p62c6OtwoOBw8F478tLnmKiyGymQHr5GjMdxLglr2kdMhCIMkUtKjGhE4pzBjD2B5oSiMJt",
	"WFdpKhEJdiRYNkoLpXDBqQ9EzvXSBY4Bqa2OcMQBhwsEX4iQ4sVT0AKSgSwMSJgyOQfeQalIcRQtkJwT",
	"gWLAVChwF2iO76EK+BbUmjLukzAEuhu58mFa6JUKpcNy0F5vHAkUMs1/OQw53yWc3JMIZiC+kZ33gAUK",
	"gRIIkb9AOJVzxu2R37E0wwslhwOcCtNIAVxpqOTnHdAMJUrGVpAiApZo5y/CFF1cX+UbWuNV7Wb6qkDm",
	"hFIIQAjMFyV0ImZcyFqSh8BREmE5ZTzegmsIlcApjj5oF/9/KxTtxj/2rsD86mYhK9wkQwZXQYRJ/MJ5",
	"5IKilMKXBAJ1KDOOUjrHNFRw6D6IBUHKOYQ99LHEKRhJjqkgQKVth2k4oeqrSIMA1FgUKRko+aKH0NXU",
	"MBrRbKCIHGABHZREgIVio4RxiYhEWCgGIkKk28gKyuQPLKXhbqSmTN5O1TAtdC6dUxAWYj4/srRQf+F0",
	"/0SxH4Hi1SmhISpOqy2wrn4l4TVnUnNRdlxsR4SK1LE3dEoD9+ZSJuOjI/W9h4MYegGLvZuO5wPmwG9j",
	"kHMWiluRJoqXINR9AIfAVasMPGU5SZmI8dER0DBhhMpiNEUDlkBtEAOeMWCmJFImA8SYRN7NMxGtBZ8u",
	"Mr5LgF5dVn0vSAtxyVBIRMDugWtJro41g3VkkWru4+ZESkJnE4qV3DUzohw1yOx6ItROTjm14k1HNejN",
	"r8fAtH5YGJlAhL7uS5UsVmcEM2pBgGmxtjl7UEOWlrgNCyqQSACfjSm3HedZGyyb2BiSXYOsupk4OO2d",
	"PdeercPidlF8n5IoRHZRiFB1ThryTjNVOqXaFrLjbYHVlGZkhR1FqjL7hLg1WkibxlzlUnOavvTj07Xm",
	"TPUxQFtlQFnA8CVRypKDEquDFIyH4RncTYPzs363P+j2Bx/7/bH+/5+ZV+kcvw5Oj8/63VH/9KQ7Cke4",
	"ex7ifvfs9Ox1OB31g/A8LLxKs96oNyezeQxxDw/6/d5g1hv0Z37ZsYN5MCdKyqRcdfny+vT2dOR1vCBJ",
	"f8AxiRbe2LuiEiL0P8Aouo6wJDSN0evBaf8j+tuHu0WE7+A700N441HHumOG/Y43S1I1R8RmJMDRGyV4",
	"vPGw48UQM77wxqejjhezECI9iZCEBhL9fDU86SvpPl+IUreB2vE01Nx78fOlgiEb5ni4gXdmSzovd+HY",
	"RlsxEonxDJ7NbTnsDocfB8NxfzQeHOd8hE9H0/Ph6Xn3+BT63dHxYNj1X4eD7skwPD8OT07P/bOSdzL1",
	"0+GwP+reD3rDk95pd5ak3ZPhSe/1Sa9/0j0LIBwNTkbrcJVliJATJcPHXj6KZxlBaxYXg75igH/Yf4b9",
	"vtIYcur/8vnq8upCTcfMDScLwa6UMl/rAyERkjOzdCpTr+NNM2YOwSdYGZ13wKnmvIjQ9Is6UDAnWKHd",
	"c5wxw1Gvb0Akf8Bb8r03HvQ7nmBT+YB5djbo5RTuP+vBPOmdekWAiz2S1bfsD9bVal2wj/onE5mEw4X3",
	"jLxtWG85a5s2SM6x1AFValosiVJWrR+FiGWG4brhXl/PcV+HVLIECQg4SKQGCkCpR0iwGB7mwCELpPr0",
	"456d/uld9wGE7A429MVPAat9ZQJhrZD8BeQD43ciD9ew8VUK1ULi4O452cgScDkf2UY9b0ms1+E+8hmu",
	"bv6a8TPtN4Xt8YBLee9wcfhvxH03u7LfCmHXzoNKAObML9xXq4+rQoNsYKsxMdVJkppbp0qQbcf70p2x",
	"rv1joZWQUPTeNDMb8sZdEieMy5IFXumr6I/lXJkXRM5TvxewuHpilC5Aj5K72ZHq9NSIZdIbeDWoPcNv",
	"CXBpA2nLG25/FqXdBh8ClpQ9Zjj8OZsui+o1sXa/Feu4KU5bX43RjNsywX4vB9jM+bYP2IQLrvZgqE4R",
	"E75pzFw9aNwR/XFxfdVcTmkTXlxfIQHawSaayMZRxB4gvOYwJV/AAdgHE3mPw5CDECixDbW/TPUtPAxa",
	"Y6xOXIG94fS/ur4foTdXl+9ro/ca+1oZvoRemZEGTaSIVFPqItIXLpLcwy84XgINZbQrJKYh5iH6n95J",
	"/xx9uPjFABXm7kWFuUChampdgsuAyUfZdPVPDnZrEjmV7FMy4zh07KmrqSJwB4H2pwuEU8m6qWmtQdLp",
	"E4rNwjQCfStGpvqWQHdjiRQTylKNGdtNIKCScIgWPYQ+ZX8TkkSRuY0xTldZpJa9EhNa0huQn9IwAsQB",
	"B3M9XKiGj8gUEOEc1Fmp6KT++DAHOTcuYpYvYEKV5RUSoWDSNz+AsC+ABmBCJohABmGIQ8JBqL2EMLLn",
	"XxUJCYtIsEBsOqH6ci833erbIcQL8W76K8DdxhEvJRJdFqM8dTxDFofg/9XCzbgmRgV8bXfaniWO8hmL",
	"ANOG8MrmuNmQmS4r8DaWRxU6CYXQ7HXtPYxIQExIBGeRIR9WVuRCWB98DgQKMJ1Qwy6MNpE95STEi10Q",
	"/SuhIXvQG4zRvY0llK25v9HS/a1MzlMu9jdaCvsb7AFCurfhNpWJtl+DhS8199pbJuvTCPFCMWrGo0Qg",
	"ewYqUamZtYOUdCJTooPBkGLiOUs5EhJzqTPrOItRH6WJ6jI8LkQketALEfp6id0Dn6oTklB7oFD4IieK",
	"GxD0Zj0ll9WIag8Nh1kg2ozQQgjoiQb9JO7oaDJMMzl6qptPqJAsKcmMqVI8TrFDsAF1CKB/KKgk04Nm",
	"g6iuMf5C4jT2xsPjTpYD5I37OVEIlTCzGSsKgvaRDYBbjV2TcGaijgZkbSlXSmVaI3o8s8JQwliESqlQ",
	"tbhyZGcoN5nQOBUS4Ugw5OeSO+O5bIbMjeVQeuuZVq5IRtsI0TT21bkxRZmNl6tjPfSzWocPKNJa2Ryb",
	"FVi0l46SNkTXV7IWsss5fu3bsHF6mCw7yRIWsdmih/SRoxWTbAN2UPnAnlC9SxTeYyxJoCO+hE4g1YdP",
	"opDKCZZgrycch05uWNdX+YP+gq4u9e1ldYmUZexL6E9AZ8oYHDj0PF6hn7HEx8d1o/mXnH5BLd3Q9C6I",
	"qMRIGGYEl2xCY0x0MCL6PWU8jXvo0kyjWeA4V+wy/Nk1m102WEn8HDtrUf2Hkle2lkZZZXhFDZf1McMS",
	"HvDiIiEVhJmk1OqI/22VW8UORrcM0VvT3Zg4Jlyihy6NymhjfaZowdIJVfBSLeF5StWfOGIPtDIAiZMI",
	"YqAyC0pjCN8zEk5oLeSwvAJGoUoBtXSXvtbx5piHD5iDASS2rrYc5imORCvQOpTY9reRwoybP5t7JZHf",
	"uGeiRp0wE/r2+lPevoOo8ZhXxVkHgQzWUDEd61+LSdzendbM5e0dPI406q/i42lAbC8m1gQ7I0q7jR5S",
	"oc3ZLA6p3fdw+csHE9tr2iqGTMVSw7XRRRvl1h53mrJ121uJRuM+aA5vMWHterWc3GVqRCoitCTsTDC2",
	"cQn4EQvunAtIWLjNfAkLt5rOhq5sM6XtusW0aynAbneiM4kWhy/IqVh4yjeyEz6oTq1eOzvoWiLpg51+",
	"JeKyy41a+nHNhWZOr81snusrtbKSw+R7faL8oiWTw72Uq062Ekapp7DbXB8BISQRWzgZGVd9SNvaaE13",
	"qEvCK3VVixWb3lL35psld9QBzai2wipqi/HTiIWQEBvLyOTi68YKzgVLnUAGNUV0IygrWuxTp3LrvNFA",
	"uWKk5KMRENYM2WiY7CB5KqeUPVfdmVLkx4pCTLZdFpgp5iyNQiXaQlDKSGjMVh1EgbL96SRW7dpr04IP",
	"ld51wZADVsBVn3AtWVGeZRs70iEvqobpxvsw6/vU8SLsg8EcDkOi1oSj66ruUC+ko5GPdFUcJ01qPsCK",
	"SXwHC9MTmYm1jpwk0QLZ8zwXmKWhC9yW0heXAW2baYTnaYmPSxdm0npcp2iZJfRIxTI2Jv9S1WsVH6x/",
	"D7ScBVddhbTURVn7tAOdgJGE9sLjz7ma+9M1hA1JvQNx2+75yrtgPbFjezjsB5srvPTSn0VpbA691Q6S",
	"jR0hbueHXbCxXbUzNHfpkD/Abm1r1lr/VZbdpW93lCCEQso6XBsNQq9dWc1WVFMD9NAkjzmbeDa3EKNp",
	"Gjkr1hgNTNnHHTTJQm8mnnY0Z0ESE+roOGc6l8dfZEmN2rugXZ5prDg5W4SXR/SUmLlA/YY51OWkCZOp",
	"9hMRDpfuT5b7Kx3yPA4dKxlgimYcU1m7FC7yepbdoLoGfiVMnq5JtVYYahH1zQ20YQq1zuD5WSfwNFf3",
	"vf5qo+h11pnOFTP5PiUK2VyfjuezcOF1bKm43YlUXp2bOnmJPH/ZUgXKs4qyDEtHws26smwHDO9ML5vU",
	"UUfDW6DASWDzAWMQAs+g0wjgZYrXho5bEveoF0jJeLCjWhUKviSYhuonmzL6j48fr22TgIXQQzrj09zk",
	"+liYdETV8N1FKudo2OsPM4MnsJ44PzUBx2ZsCM1qjVMbJOYLW0lAT2Dk5sX1lUBGXFhnPxNQusDyF6X5",
	"ytKkmexfSy+t58uUUxJLieeGs27VV3uR5ili5ox2G0NI8K0sik2CkLe2rqdk7DbCfAa6T8KZzsj1I7jN",
	"whE7paxp10ZyZPHUyfcZuK+QYtkBma9+lj+sR3CLlDzr57GRukh+TwHpBshUKZ0S4EXekwFztU7ansvr",
	"0lM22yOFrvGTUtc/K83dxdzGH1U6kbR2bzT9jjoC7amsc/oUhHm6qRLGJdnvw4QSGsKX4uZLaV6K+XvG",
	"vyqBqzn//2/97vlF95+4+8fN3/4+Ln7r3vZuHvud08FTqcV3f/8Pb2cR2pbQ2MCHTWfEjnTFPGNwUa80",
	"5bDxXBmk+5SnbQf307J01OcS6NnMvBWtHytnTdZug/O9mRa714RHNbqBouFIsCB1WqjqWNoSEuy+rctR",
	"z0vcrCa4791UhxPv31iruXQfaxugHpq9slB2SYhWSuz4EDGqq/6uFqa1SZuovqn7NzIIiiIS/qK6Lk3b",
	"UoY9B7xVwZfVfvFnItia7NIkYSlKflkx8H0QrphqW5plq9kXubIB/lFJXHDhoVTiSXu7ccXcybStlN5R",
	"9kDzVIiFTsrSDvU8F3kPhkLDldJYchN72qSOIn0JXsWbKZDFiXRFrCxVuT6WOaH0ydZ6YYnxVUYLhNNZ",
	"rEM3ZXZjoHXemOm8Oyrhi3QeB5lbcH8bxakuKS0Qz/Z8dEs8cx41GqabrYl+7chRadm5RZWytfk2AW3t",
	"1HJhyr9qTg6h9nnfrP01ZKZxRb1v+iUfG5vAVHEz2U/OEv0khqpgNKWQIpAmOicPeAixhK5q7mL3eU0O",
	"7f9Ar0i6J3fG03PM6+Bax/FQb1LDyLbHhpJ7O58Vhe7Y7pZ5d3X5xhxOpbziqgguK5cVH8yeXV0C4vu2",
	"VxZirGyeUkmP4j2F+0Fv2DvuTeg1hy4HXTTJnBA2idx4OnS9vJRzoDJaFO6mmv13P5mE/3cy6ZX+2YON",
	"56ha0nTlbVqzpKNEZJxok9b4MyfUJxTzBcISWUTobd5D6BLuIVICAvlqHpFVlcrm6/fUf42z1H3HpcSH",
	"XUT5vh+1mkhLL3CzkbIV28YdE4tsqbvuHVo20+7WTIuofWbrZYlIN7dg4fcLNxp1LbmHObO3ZWHDwd0M",
	"SahkyK5/RtgJ1j8jSIumnhpnVT64ucBp5iixULsMV0JubgfXgDwbcQXkuAq3HX5duGsMqoMGKyhf42ww",
	"ZeWyA4KIipfLCux/pcKWVTPB+CGjr2QmwicU08WK8q/GvesDhSmRJkZCX3rpLDTyB4QTmi/BAN6bUG/n",
	"DSaxM/5d4hmKcZLopXKfSK4kmnXoMeP8EzrEAwSYoomUGb8yjvQlmI56N/dxC5TvTPMCkS4hIUH7sFWT",
	"VIA6bnWigdD3RSbTrghb0GG2Sts3GWsZ8ju6u00+V58CLGGmy0EhIteVpBfZHlBQt4tPt4NUP7ijox5s",
	"LJPEs/UFpR7zZh9UbNMwsmtpaUOsn+HuRvHQSr1ji8fHXNeAjufTNokJzlZBQtF7V39jbUkwcKnfGqHA",
	"WetKIPAub5c56Fp9bW1bHFyXnmT7muCvDj2rFkxqZBBcf0LlFmWjNK+thFWL09Ea1uW6Ra9chGhLJXme",
	"aJhW23OtmJjtoN46cGaH6TZAdJ1T9omAythPHc/HHBTkUXu+rjaJTCwMyYJXQgh1knhYDsNpJoGUSsw5",
	"wOdgbS3F/KZ6V9l5ZjR1XTPMZgR1GlukqX0mbW6gIovszfUn4Yqg6eShQ83eOGYp1ecOJHOIgeMIqdbK",
	"Znz7vXs0Wwptn+SbJalh3qI03vLVmlZ6laRlmQmhFMJ31EUlnaGm85N0Wr2+FUyFuUpWzGDYQucCmjt4",
	"nWxK6JRjIXmq6fQepkqTsY7zhdUp+AykvgFbIxdHEzWH2JKpU90n+9uuS4Ph8jKAWykea4vlldrHWqzy",
	"sym82ITm7fWnysbqeXs4UbIJVylu9cmfD5k5CvaDTrccV+BU4lqaAr1aHdO1YW2LkpB6e/1JIHyPSaTT",
	"+7BAAoqs7ncf3Hu5TShonK8WBfFKhnGnKFXreDqd8LZJHcK/BZiH4rsCUvfCssqQe+ePz2bgusSx82UY",
	"KcmeKqydKm33IYSKRTkRqShhVldWEW3BzI6um7oP9VCnMzgNFv3lr6kdatCy81VscQmw7hRuv39dA83X",
	"sA+20hO/tcVZnVxlUmsRmSJChcSRLcVSuwGydV1XDJJ7W+0TBJZlc0HZ5j+D6NkOgSxm508TJRZ1eyPm",
	"uw9uh4J5WYnOsnyyUosmPYvKussUdNXK3FZrnfwBc7k48gmjLZTMivPuF8dMXJpxn4piv/uewZorT0Xx",
	"4H3P8KMZ96lUjXgZ6m0jg/gQxJ1kyZEZbLNLEXtNVHuAq2ATPcHEVEE2z38v9/hZ/OSkyKm+yXXJJjJ5",
	"g8Poa1rQz2Dl5bI6L4C999HffahUum6EzdjSK9rEVa2Ky1ubfat4yOQ8LlMoXdWz9wlLY3xHFe5nwN7n",
	"6hSN4j0WrY21aHI+g+GaaxUt/nxT4fuV0AXpgkUQgQmEqaTb5AEv5jpJ/2jqk3fsO0v70yyXxevoBq+E",
	"vUZqbm6Rwfksehm4SjHJPZLpc4M96y4XLHUiVilnrLzbtAuuTLhykfmyQ6/jYbrYH8mWukU2LCH/TPa+",
	"MVr2YOznmoYDZH3KET9dHpuwtebhUgaMa5RNG4e2yJLSi6yF0Baf0slOOLhTPGOvV/ezzh9zvai+TqMR",
	"mCTCEn+axxf2wYemRXsZpjz8KKtkYO/sdW6jftLUPHOnL1b1Y0oO8dKst99WgNTYNtR4wi3zlya0wUCi",
	"5PuwQ5qX2xiFUjGBUlihKchlU22zojb6alpXbcriYszLBcLUjqjP6WMBXS0H8rxTc48v9QV3bKuzlGZV",
	"C0K4WOznny5+0bWSyrfybR7aBtL2IS7LRSDqhLbwbn5ZaDqSUPTem+FX3BTm7de4JzRtd7olNC3aKmeb",
	"r187UX2bcjbbwf3VLuZK0zW3dylIDvssLW9qR4G9NYum7Cjr8kPtOWb5qEauo91mMObw7Q/tHy0gbWno",
	"r0TxHmn9MCleOymXMVCsQeI0wnJPSmr23skSlSd/7eSZlJmSJNiDRuMyxNqKqOzzXT0de9uos3KlVdmE",
	"Q+5pzENGs38dlXQKvmt7s8F9VrQ/1bBzEb7PbQv5OrX4lj6d0vQAtePhmyyZ1gb91qfI0gE3QedahdS+",
	"Ro2rjUpOtYG/duWp1fWm1pli2RZeUWuqvZjLxzyI5ZVAene2plg1Oz6sU31pWRGYavxJXl13RXVaG1OZ",
	"A1WaYVvcLjOanDhe/3xbi7SOk6y1n7uQ06pd9w0VdPpq8mupHrP0IaMdad+mvdjyS66Nrr84nH7kD1el",
	"7dw93e6EdvhmHcjTlU+DlBO5+KAz9E1aty6cUn1x1llCwT4DbScSRQ2SaoGa6nu7WvWI2EOzhMIbFjZf",
	"5v7Eo9JT2llMao/eiR6kCln6rcFRj+pCUVqJMOs/uh8eVUbKc/i98aOijlrbTqPrESolqPQn84IWoVO2",
	"ssjiB5uuc3F9lSn/oigoa/yK5k2ORtaBfmRFO7Un1NTbjIEuq1wmiYygWhOuNH3lTdBBb3Dc6+t7GLPn",
	"vbF33Ov3jq3Opkl31HuAKOrqzNEjU3ijm9d+6LbXiLjKSnALky/XrAillpQX4VBLn4HjuvC9Tl7WYUFq",
	"mKJqR6IdxjbuTqPLVcxKjcsyFtZPsL0F+StE0Y8KoHcthUR08Qv9mp7GwbDfbxMSebuj/b5xr3jrS3du",
	"auXYIupfupR1s43ctdtRo9g+m/nU8Y5wQo7uB0flyHtx9FiJ1b98yt6nilvfwCqRr17utcSGGQ8Xzyhk",
	"I9ofTIpdwcQtjNtBcs5ZOptXNkDHPjahf5QMZQm6vQltTpcKiThMgetXhXBmakGIHC8Z6S1XciZPaGZC",
	"Zv2E4/mvIjHGuhuVaWWr2GNBhK2oZp4zmNDsVZJpSgNjiSqZ08bnPxHRxLWpUm/D4so0dLL1RUI+D8p5",
	"EqKaNPGmRvRtuLz2eFrBrx1vtP9d4uPwvam+VJ1osO+JnC/T66mO9z1VXgKrOs9o3/NQJn9gKa2Ac7J/",
	"EilVhFMcmapFukxaRYhl8konf7pVjt9unm7q0u5JHUGZedmaOFo0OapKuKIi5NPNxlJxyRsYucBbto11",
	"Jnp+xfEMO3i7rXvX/mTsYfcedu/L3L2dlV03zn78oN8YYnw7GWEdfOLoMUv4O6hTf6469dU4LSd4mXM6",
	"XsJcKSFvtL9GIIwoPDRALx0KdtTmeXDNxMoDwWaEijwz1KXjaRH8PQsX7dIja0KUiqdXXn4/wUpxWxSw",
	"fOwMN9UYD0fOvo6c833Pk9WB/UaPnP2K8KPH2rsol095jSjnq3gRmN1e3+m6NkRpu9uidtmun9CPNokA",
	"owCLAJsqxLnTTVdtI1Fkq0xp1dIMHVbcPlXRYZazq/BwvLK++fbfsBBqEEAi61vqICYOmun+NNODZvZv",
	"oZmt7lWX8DW1LnVodZ/03ZtLzreL+KZil8pnEc1/rp53EPQHQf/X0wfX9AV+Qzbofg3NHSxMx4X6DuLH",
	"8RjTQbIcLM0XLFlyE3Mt27JQOfZt7lXCOg/n/uHc/2sZeC/uuF7dq/nu+vq2yTI5sYPhURMSL+DAP8id",
	"g9z5i2sFWhCY16l2CEl4C7IQCq9ExS1Vf/lq44iE1fLixwKGvUQtFOMd9vJhL3/z4QvPoiHsKItsxHu7",
	"CyTLUwi+UVfIfXX9e3KJfK6hbWtF6XNrxsEO+lJ7GsNBih78JC9QI6pJoY3dJSs3+ZZuk9o2P3hPDprP",
	"X9d78mJP+tW9WvPoN3KmrFYVUrlfEfJyVIaDcDoIp38PhWKpp2WZDFzicalJjmf3vLQJlYMD5rDTDw6Y",
	"P0W5WF9gtddkCgIQ+nVONCWRBA5hvUpT/iqbrkYZkqkODpS5vJKLBERvQj/Zyra/pyZ/2q4TSZa/bwJE",
	"v4qT18n7m48FhIhR9Pln80DohOZFOE2tj+8Q47ms+5t5gNIi47tyqcxSSaklCbAYBUooQpgV7ih121hE",
	"vrdI3T2de+2iWgeRuB+ReJBVrq5FibmdpMzRo61rdPl01PosUElZsS8hrZX8KnSKQkXTyUWAnasoJqqf",
	"IZ1jgbCWckiyXfZ5VvPyBwvS19j2FqTDtj9oQn8R6bKjBlOWLW2ltUvSwdT93lmylEt0P59guTLwfA25",
	"YgA6iJWDWPk3Fys73UUvL9FRc9Dst1SH6zJ4U6HRWvLuIBcOcuFQuKMiSNpehsqK3/kpiYpCzKQog76k",
	"8pxMObVpj5XeQuI4gRARKpmpn55SXbHPJxTzBcIScYgAC5hQSWLomPJ+qoV9mUG7Ut5coZl5XIGpobX/",
	"5QsOZLRAD3MSzLNB9DsIISQRW5hX65zCyCLg+UvXWQFrJ/yTJMRL3lIijWPMF/YiQPFHRry87uF9Ti2J",
	"Z2qjZS+YeTe2zl+1pqW9/3h6+t8AAAD///HQeolK7gAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/identity/v1.17.7/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/region/v1.17.4/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
