// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/region/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9C2/bRtboXxnwfh/S4kqyJMt2LODDwo23qdE2MfLq3q1yjSF5JM2anGFnhnbUwP/9",
	"wzz4Hurt1EmFXaCxSM7jvM+Zc8589gIWJ4wClcIbf/YSzHEMErj+K4hSIYFfXV5nP6tfQxABJ4kkjHpj",
	"790ckH0PXV32vI5H1M8JlnOv41EcgzcuBvI6Hoc/UsIh9MaSp9DxRDCHGKuB/4vD1Bt7/+eoWNOReSqO",
	"blMfOAUJ4hWOoVjPw0MnG/1XTPFsg9XG5v2Vq87HfZTFMz7DlPyJ1QJXLr38cvu6q0M+yqoTzv4DgVy5",
	"YPte+1rzgR5lmRxm64DVvNa+yGyYR1zju0UCK1YpFwkgNs1Wew8Ic0BY3BI6Q1PG88X/kQJf1FevJth6",
	"/a41qrWnlNwyTrtBxNLwJmAcbu4GvcFZb3CT3M5uWAIUJ+QmYHHM6I3Es7cQQSAZX7LVCyRAqn1KPBNI",
	"MhRjGcwRnmFChUQcBEt5AAIRiuQc1M5jNNGb/Z87HKUw8ToTKuepQPdzoAhowEII0YKlaAYSTbx/SDz7",
	"nylj/318GWA5Sfv94an6ycf8v48vQzabeG2wlHjmlYFGJMRaVCrkeGNPSE7ozHvoZD9gzvHCezCI/iMF",
	"IX9gIQEjXjlgCS8YlZxF1xGm8Ma8oh8yKoHqf+IkiUig2fnoP0IB6bMHn3CcRKD+GYPEIZZ6PXaZIUxx",
	"GkmNo/UwXJV1v3Eiway6ihy7WJSo1SK7I1RojV6DxJR81vv8OeeBF2aufW3WLl0BXSQQqCeWYUNv7Pn9",
	"k3P/GE675xhOuqOhf9Y9H/mj7nQ0nPpn+NTHoPjiDrgwW7wb9IZnvaHX8e4Zv40YDq8Zi4Q3/v2zh1PJ",
	"RIAjhWO1GEJJnMZvQC9ZeOP+Q8eLcTAnVC92GuE7xvUygrOT0+cwDLvTc+x3RyfHYfccH+PuyeD47GR6",
	"9nw0PPU17LKhjh86DWx+XB+ft3Vot6K0wEuuGTfC6wfCZYqjp43eJio3x00NG1VkbYCauxaAtWLIQhht",
	"iykte0TCqICyWWd5/Y19tD2iNB0o/UA0gIb94XG3f9Y9Hrwb9Mejk/Ho5N9ex5sDjuT8rcQyFd7Y/qlE",
	"K9kFBxVbRw0Ujk77/fAUunB+etId+aNRFz/vP+8+H0394RQfn571FW9ndoeeG8NwcB6edQd9RUOn/UH3",
	"eTAMugBn0D899c+PAzCf3BElJAid5dvIf4Rwa2n7BnDowvtF3VTteQ1rV2yDvt8P+HPj7+N2CBRu7EVE",
	"aEOmhkWh0dgQ0Iq7A0anZLYGSlkgQXaF5IBjb/zZNbtDWpjhU67HcK/ia5QGmYZ4YtRU6KuaI6n11vOT",
	"k+HJNOiO+gHujp4P/S4O+mddCPBzvz/w++fB0Os8miFTMlJCIm7VfwX5E7zxiTJhnpLd0i4cmwTuJumv",
	"U0QeiPrpE/XHral6hcZokrZRGpv52zgIIJEQlunfFfwwJuQcC+QDUJR9hjAN0T2JIuQDmqbRlESR+lUs",
	"aDDnjLJURIvehP4/lqIYL1DCokh75JmLrgeIGSWScUSkQGXy0g8NhyChSW1CJUP4HhOJFAgj0FEuNtVj",
	"sgRKamszOPg4tM7IdtoNOGfcG3uE3uGIhDcWYl7HPLmpwjSDp8/CBbKfeB1PchzAjRYEJ2d+MBiF5344",
	"Oh1M+/4JPhuG/vPj/mB07p+eYW9tabkZHMw+HIT3przkKSYKzWYKpJevIdNBjFv0mrdDBgJRprBFJSZ0",
	"QnFOAMb/QFMCUbgN6SpLJSLBjgjLRmnBFC4o9Z7IuV66wDEgxeoIRxxwuEDwiQgpnjwG7UayLQuzJUyZ",
	"nAPvoFSkOIoWSM6JQDFgKtR2F2iO76C68S2wNWXcJ2EIdDd05cO04CsVyoblEAKVBEcChUzTX76HnO4S",
	"Tu5IBDMQXwnn3WOBQqAEQuQvEE7lnHGr8jsWZ3ih5HCAU2FeUhuuvKjk5y3QDCRKxlaAIgKW6HApwhRd",
	"XF/lDK3hqriZPiuAOaEUAhAC80UJnIiZoKuW5CFwlERYThmPt6AaQiVwiqO3wO+A/1OBaDf6EXogC2w3",
	"CVnhJhkysAoiTOInTiMXFKUUPiUQKKXMOErpHNNQ7UN/g1gQpJxD2EPvSpSCkeSYCgJU2vcwDSdUPRVp",
	"EIAaiyIlAyVf9BC6mhpCI5oMFJIDLKCDkgiwUGSUMC4RkQgLRUBEiHQbWUGZ/JGlNNwN1ZTJm6kapgXP",
	"JT0FYSHmc5WlhfoTx/t7iv0IFK1OCQ1Roa22gLr6k4TXnElNRZm62A4JFalzY7hOWeDeXMpkfHSknvdw",
	"EEMvYLH3seP5gDnwmxjknIXiRqSJoiUI9TeAQ+DqrWx7ynOSMhHjoyOgYcIIlcVoCgcsgdogZnvGgZmS",
	"SLkMEGMSeR8fCWkt8HSh8XUC9OqyGntBWohLhkIiAnYHXEtypdYM1JEFqjnBmhMpCZ1NKFZy18yIctAg",
	"w/VEKE5OObXiTR90a+bXY2BaVxZGJhChD8hSJYuVjmDGLAgwLdY2Z/dqyNIStyFBtSUSwAfjym1HedYH",
	"yyY2jmTXAKvuJg5Oe2ePxbP1vbhDFD+kJAqRXRQiVOlJg95pZkqnVPtCdrwtoJrSDK2wo0hVbp8QN8YK",
	"abOYq1RqtOlTV5+uNWemj9m0NQaUBwyfEmUsOTBhiO0mxoRW5rdWhwkvPEKsaXB+1u/2B93+4F2/P9b/",
	"/3cWUjrHz4PT47N+d9Q/PemOwhHunoe43z07PXseTkf9IDwPi5DSrDfqzclsHkPcw4N+vzeY9Qb9mV+O",
	"6mAezIkSMSlXn3x6fnpzOvI6XpCkP+KYRAtv7F1RCRH6FzCKriMsCU1j9Hxw2n+Hvnt7u4jwLXxvvhDe",
	"eNSxsZhhv+PNklTNEbEZCXD0QkkdbzzseDHEjC+88emo48UshEhPIiShgUS/Xg1P+kq0zxei9NlAsTsN",
	"Nele/Hqp9pANczzcIDSzDZKXB2/sS5uTEInxDB4tWjnsDofvBsNxfzQeHOcUhE9H0/Ph6Xn3+BT63dHx",
	"YNj1n4eD7skwPD8OT07P/bNSUDL10+GwP+reDXrDk95pd5ak3ZPhSe/5Sa9/0j0LIBwNTkbr0JMlhZAT",
	"JbrHXj6KZ0lAGxQXg75C/U/2P8N+XxkKOd5ffbi6vLpQ0zFzsMlCsCulzNdmQEiE5MwsncrU63jTjIxD",
	"8AlWvuYtcKppLiI0/aT0COYEK7B7DtUyHPX6ZovkT3hJfvDGg37HE2wq7zHPVIJeThH1s4HLk96p+tAe",
	"AFtNrJ5lP9gIq428ftb/Mik8OFx4j0XVhu6WE7V5B8k5ljrtSM2JJVEGqo2dELHMGVyxBPP4y0Xq69uU",
	"LEECAg4SqYECUPYQEiyG+zlwyHKN3v+85yh/etu9ByG7gw2D71PAiqNMzqYVjK9A3jN+K/L8DJuCpEAt",
	"JA5uH42ALPaWU5B9qVfigJ8Pp49f4KDm28yWaT8XvGtNl1lKe4djwr8R9X3clfxWCLt2GlQCMCd+ZzoW",
	"Dl1JsY1UII2GBLi02aRlOtyfW2Wp423AknLYCIe/ZtNlqa0m4ez3Yh0fCw3kqzGayUsm4+3pbDaLQO1j",
	"b8K1r/aMoE6RSrxp4lg919iRAnFxfdVcTok2L66vkAAdZRJNYOMoYvcQXnOYkk/g2Nhbk7CNw5Arbzqx",
	"L+qgkfq2cLO1FVWduLL3RuT76vpuhF5cXb6pja6+auRcx4RemZEGTaCIVGPqItKnDpLcwSscL9kNZbQr",
	"JKYh5iH6V++kf47eXrwymwrzGJuCXKBANbVxsWWbyUfZdPUPDnJrIjmV7H0y4zh08NTVVCG4g0AHlQXC",
	"qWTd1Lytt6Sz7hWZhWkE+miITHWoXH/GEikmlKUaMvYzgYBKwiFa9BB6n/0mJIkicyRhIo+yKLl5Jia0",
	"pE6Rn9IwAsQBB3M9XKiGj8gUEOEclApReFI/3s9Bzk2clOULmFDlioREqD3p4w9A2BdAAzB5A0QgAzDE",
	"IeEgFC8hjKxaqAIhYREJFohNJ1SfcOW+TJ0dQrwQr6e/AdxunPZRQtFlMcpDxzNocQj+3+y+GdfIqGxf",
	"O2L2yxJF+YxFgGlDeGVzfNyQmC4r+20sjypwEgqh4XUdQotIQExeAGeRQR9WntVC2EB0vgkUYDqhhlwY",
	"bQJ7ykmIF7sA+jdCQ3avGYzRvY0llP+1v9HS/a1MzlMu9jdaCvsb7B5CurfhNpWJ9rsGCV9q6rVHLdbP",
	"D/FCEWpGo0QgqwOVqNTE2kFKOpEp0RlRSBHxnKUcCYm51AVZnMWoj9JEfTI8LkQkutcLEfqMhd0BnyoN",
	"SahVKBQ+yYmiBgS9WU/JZTWi4qHhMMvGmhFaCAE90aCfxB2dUoVpJkdP9esTKiRLSjJjqgyPU+wQbEAd",
	"AugntSvJ9KDZIOrTGH8icRp74+FxJyuE8cb9HCmESpjZsg21g/aRzQa3Grsm4cxEHb2RtaVcqZ5njRTq",
	"zDlBCWMRKtUD1ZKrkZ2h/MqExqmQCEeCIT+X3BnNZTNkoR2H0VsvN3Kl89mXEE1jX+mNKcpcn9wc66Ff",
	"1Tp8QJG2yubYrMCCvaRK2gBdX8lawC4XurWzYUN7mFIzyRIWsdmih7TK0YZJxoAdVFbYE6q5RME9xpIE",
	"Ou1J6LpDrXwSBVROsAQbqXcondzfrK/yR/0EXV3qI7zqEinLyJfQX4DO5LxsyRV2Hq/gzzio4+O6L/kq",
	"x19Qq7kzXxdIVGIkDDOESzahMSY6Iw/9kTKexj10aabRJHCcG3YZ/OyaDZcNViI/h85aWP+xFKms1RJW",
	"CV5hw+V9zDEP7zGHf2p2iW1UJgfcFEcC6sD7Z2bl0hBl39sUUsbNz+bkQeRHsRn7Kak7oS+v3+fvdxA1",
	"kdUqi3cQyGANs8ux/rUAZ8O5a8qlbIntXlxIdfFxnq7R7p1evnprUiDNu4poUrHUtWl8ot0267E5nZ26",
	"d6aYxziYzeEtJKznp5aTx5oM0yFCS+xgclaN0+hHLLh1LiBh4TbzJSzcajp7wr/NlPbTLaZdy0RyB5yc",
	"tYY4fEJhpyLEuJEl+VZ91BrXsYOuxaBv7fQrAZdFhWtVmrUgS0I2t4qvr9TKSi71D9qjfqWjn44ARK5c",
	"bYl96Uth2VwLxBCSiC2chIyrUYZtrfhmwMylbpVBo8WKrQKot+4wS+4ojcaottMris148mIhJMTGdjYl",
	"y/pltc8FS52bDGqmyka7rNg5D53KWd1GA+WqU8lHIyCsobrRMJkieShX3ixpg1ERPmWoE+oEVn407hqz",
	"xA72vSxhTcxZGoVKloWgdHFoPBl90IwyhnROWDsg2LQQvvJ1XRLkECr2VZ9wLeFQnmUb18IhIKq+ysaM",
	"l3370PEi7IOBHA5DotaEo+uqsVBvyaGBj3R/DSdOamGhipd0CwvzJTITa0ckSaIFsgo8l5CloQvYlsq6",
	"lm3avqYBnpdrfV66MFPu4FKbZZLQIxXL2Bj9S22tVXSw/tHAchJcFR1v6RextnoDnZiehDYG/tec1vzl",
	"JsGGqN4BuauPfqqdhpaLIM0IDdtSGfW2tksxP6PRAkXsXqEcC0DBHHMcqG10rPMpFBHMF8kcqOjYuI7y",
	"tUAXEso5wsVHOqKtvzJxKzWvRDETEp0el8ZGhKJIe9M2MpS51qfHKz3tskhYTwbbLxzeky0oXXpWzKI0",
	"Nip/dQBh40CBOzhgF2z8WB0szEMe5E+wcs66uDa+k5UA6dMPpRWgUDkO179B9Ws3rMrsiUUCPTTJ85Qm",
	"ni1Aw2iaRs62Jsb+VL5yB02yjI2JpwOx2dn6hDo+nDNd8OEvsso3Zer1dEgwjRVbZ4vw8kSQEmcXoG+V",
	"RH2XJCqY7hel4D4oXeciOMNWpWVrfWh0Y0fByaJOVwcoLOWFK4pBbfZdgCnyYUIJDeFTET5UssrHxk1P",
	"sJTA1Zz///d+9/yi+2/c/fPjd/8YF391b3ofP/c7p4OH0hvf/+O/vJ2Bka35p0qWi4s+StW/2sIvV7gU",
	"GEvpLWX3NM+bWej0Pe1E5Gnqe8BhQ5s0lpw9KZW3KkaKIn0InKNKuckmxHSvVKgrElMe1s04Wb1S8ciW",
	"AbLEmGvRAuF0FusDTZl5SVrGxkynZ1IJn6TTVMsso6008fr0r0QHnon9ziTx7BcipNtG+7g10q8dCU0t",
	"7QyLAva16TYBGirYVxOnyn9qSg6h9njfpF2Jn5i8jtdTnWC1PwQZBfSmaZp9bjCBKfA3qXLOfockhmo/",
	"AVMlG4E0MWtTT+ONPWV1dtXrLnKf1+TQ/vbqlHQP7vS4x5jXQbV1vnAspQaRpl37sbNS8Cn9GkU1mdfb",
	"nDIFxHdtPSBjTCUJSuVTRbfHu0Fv2DvuTeg1hy4HXaBqRK7N3DepEbo3Qco5UKnsoaxgsKYh7yaT8P9O",
	"Jr3Sf/agBVv44JG4jq/mN+OlhT8s3Myma8Dv58x6c2GF8dwxskqu6/oMbCdYn4FJS7gqpeSPtDS4samb",
	"TgALdTBw5c6N97rGzrMRV+wcV/dth1933zVG1tWtFZCvwbimHDzjXiIqNqU1J/+jnD5dDm38sJDRZzLj",
	"9AnFdLGibUsH+alyGylMiTQxPO2H6MQ55YNMaL4Es/HehLriPBtbAi65IfEMxThJ9FK5TyTHfJGZz8yY",
	"2kKHIEGAaXZAmYkY40j7Jfqg3rhIC5Rzpum1qytBJNDQGn+pACULdW6EUM6qTQ4swmoTak0xk2SXAb+j",
	"P7dp5OpRgCXMdBknIrJpMrqjWRcZD6hdtwSzOt6d2x1RdGqicja4LvFs7WCYGfPjPrCo7bklYRNpT4XX",
	"ipNsTkOOGMqGXZbKZdWml4V7S7/YDVU+yCu9c99uxrEit0rGbFkctaeXugZ+JkwnH9OMSbnHrXSyGxhM",
	"jf+vusS/ubof9FNbZ6v7UuhuEqYjQMlott0AOp7PQuXomfbLG5nAK1fXRnD2TMxftlRRmBFZDxZHSf7O",
	"1Loawjvjy5Z918HwEihwEtiOITEIgWfQaZT7MUVrQ0cKmXvUCySBC7Cj2sME+JRg7RhlTWV+evfu2r4S",
	"sBB6SPeEMbacj4VpWKJefH2Ryjka9vrD7KwvsCkZShXprFg9Ntiwo8n4AalUgVFaegKjDy+urwQysSKb",
	"CcUElLL7/EVpvrKD12wHVmtAU6+oLzctKbWmMpR1o57aLENPITMntJsYQoJvZNHAHYS8ASqJXNxIxm4i",
	"zGegv0k40z17/AhushKmTqmvkouRHHX+dfR9AO4roFhysGEJP+swpEdwi5S8L8DnRnMTo7jUC4jojk5T",
	"ArzojGC2uVohtXf72Ug7DQ5xvS1bnjTgYRueYEdDk7ynyKLei9Zx2unqMbNPedqmuB+WNax5LIGezcxb",
	"wfquomuy9zbQ783GOXttiaJGd8bm8i11WrDqWNoSFOzO1uVKySUZRrv76oO1o3FNf71ezrnyOpiSEK34",
	"3D5EjOqbNFYL09qk28aGKuvSuA03ihVtmRL2SAhbk1yaKCxV1i67G2cfiCum2hZn2Wr2ha6nfww0OBwD",
	"7VcFPMox0GC/x0CDv8Ux0OALHgMN/kbHQIO/6Bho8M0cA62wHdvDMq+vLl8Y5VTqQlQVwWXjshKD2XOo",
	"y9H9rxnw2rT3n86XihPt+Jmo34T6hGK+QFgie8ilmaGH0CXcQaTYCPlqHpF1Z83m6/fU/9aMIisms4so",
	"J4QvCSgvS/jNRspWbF/umHJGe3K3dpjZzrS7zf9o53GDw3nc4Tzu73UeNzicx30D53GDv/Q8brD1edyK",
	"XnTVhpONmtPr96j8RtlSz3tTYvXG6WgNk3utdqEuYLZVHu+cKb9ZUtZa+fJbbHnrjPpt59oAxHUC2dvW",
	"KwM/dDwfc1B7jtq7uuiMJpMRTrIU7hBC3UooLCej12uMKw15HXvnYFOlFMGbjqflKIIxxnSf1SIJv8YW",
	"TQMjafOHi14DL67fC1ceeSdPoG9+jWOWUi1aIJlDDBxHSL2NCEUvf3CPZtvH7g13syQ1NFt0EV6+VPOW",
	"XiJpWWNCKIXwNXWhSDcx0Dcw685L+mwkFeZATVGCoQndLsKcROp+JIROORaSpxpJb2CqNJUNHy6szuAz",
	"kPocYI3SdI3RfMcWR50qh+yJS5dWxuQdk7fSKusJ4V31yixJfzWtqZv7eHn9vsJMPW9XzZHNtkoZ12d+",
	"JBjmm98DFN3yWm2kcpbfFNzVtuEu9rRvlOTRy+v3AuE7TCJ9lwYWSEDR5uf1WzfntokADe3VjB+vpBN3",
	"R4Jqg3Nn4NG+Ut/hdwHmofi+2Kl7YVnj7P1Sxgczal242MkycJTETHWjnSpid5Y3xYqcIFQ4MEsr2362",
	"k3hHt5Lf2e7TNczOFC395Bs0+/S+Mg0qtgh2rjW+O7hZtyvzBexMSnrWl7ZTvZOSTBcZRKaIUCFxZDvx",
	"1WLctsn9ikHySJm9hsmSaS4W22IfED2OsM9SEv4aqWGBth8cvn7r5EZ7qSSdZT0iSm800VjcLrDM4FZv",
	"mWM4bWPfYy4XRz5htAWB2QUFe4QuE5dm0IfitoO9Dm8dj4fi6oS9Dv+zGfShdBHDMojblwy8QxC3kiVH",
	"ZrDNwtc2oF+7crSgDj3BxFwAMfFWx2YscHIk5MjeJLC9tuDdQN18MRd4325aLpDzKz/2O/Trt5WLPRpH",
	"/7a3nvZO1VvFAZRtnqPoxnQwWWYgui4L2dtGGoM7bhzZN9w+VMdv9GW0AG0sRGNx3w5nbiu0BFnNVSbP",
	"hG40HCyCCMwZfqVMPD+rNzF+/U9zC0vHXiK5JzNxWZ6BfuGZsIH9Jh+LbJP7t7PA1VxT7gs7Hxr0WA+P",
	"YKn7BpRaHJR5S8fKyvgq36BTjrx1PEwXe8LU0hDGhvfjPIaTbryOXT303HhwbFarL+Kny4+HtzMmXCre",
	"xC3ZtKGKRdZEqsitDm3/UF2SgYNbRSf2eGsPi/w5t3PqizRK3jS5KBGkuUpqZ8Izj9t7aObpEVmTMXta",
	"qhtv6EvZzUW9+khLXwfpECPNC4Tauscbz4SaALWl9tKENklXlOIUdkhz9yyjUGr7VUp7Mt1UbVOcrN+k",
	"PhREJC4yEsxVTMK0davP6WMBXc31eVMUc4Iq9dFibJvblGZVC0K4WOyHXy5e6aae5fPQtthpA2g7S0bz",
	"uO3+D/P0S4UO+A4tF7fY9Jc5LyrN1aTwUoYO9llapmtHg+A1W/rtwuu5IN/7FO/UsHVo2/KifGd7gvY7",
	"u4W27kDPRHGXeF2GFheXlftaKXIgcRphuQ8bLLu6bIlqzy8uewylXWL6XTW3y6to6++3xyCjaeHQaAF4",
	"pS21hEMeGMuz07L/Opo8FrS29N6vpuveet/S19m2tm33WwvKpQNuAs61mtk+Sp/Rjdp+tu137e6fq3t+",
	"rjOFs1rQAndFv8/2HnLv8qyBZwJdXS5L7m9+eL9OB8xlveeqB/550/sVTeNtnlK+qdIM28J2mTnshPH6",
	"Inwt1Drkdet37maaq9jsK2qq+cUE1lJVvfTavR1x36ajbddHF6PrJ46wDfnTdQFGHlRsDx064moO4Ol2",
	"80HKiVy81bWhpqBQl+xXb0N3Fu+aktwstCmK6vdqa4TqXfA6jTZi983i3RfMdAqv/PieR97Ym0uZiPHR",
	"kUlhkYsevRU9SBWw9LW4ox7V/Sl7AYuPzPqP7oZHlZHy6lFv/FlhR61tp9H1CJXOl/qRue+R0Clb2ej6",
	"rU2Bv7i+yoxbUXTxNyEic1VWI5NX332mY5ITapqcx0CXdY+VREZQ7ctbmr5ycfWgNzju9XXo3PC8N/aO",
	"e/3esaksn2vUHfXuIYq6umbpyJR8d/Oq4257dfJVnJjLLYSp1Gj2IlFLysu/1dJn4DjYeaPL5nRyhhqm",
	"qBdPdODP5jppcLnaqKhxWUbC+sLQlyB/gyj6WW3odUsJuy671ne/ahgM+/02IZG/d7SX4vn8yllFW5+6",
	"c9OlQd/frP6mrJsxcteyowaxveH5oeMd4YQc3Q2OyjWq4uhzpY738iG7NjJuvZqyhL56j/0SGWY0XNxu",
	"lI1o/2HKVgoibiHcDpJzztLZvMIAHXsHlP6nZCgrDetNaHO6VEjEYQpcX/aHM58CQuS4YFCzXClAOKGZ",
	"r5R9Jxy3chbJ5jaQNGU8NrTpY0GE7eVjbhma0OyysGlKA+NyKZnTRue/ENGEtdCxYpucVMahk6wvEvJh",
	"8LqM+NcVtL+oIX0bKq/daVrQa8cb7Z9LfBy+MX0/qhMN9j1RSjPpoXmxNNXxvqfKm69U5xntex7K5I8s",
	"pZXtnOwfRcoU4RRHpl+GbtBTEWKZvNIFVW6T4/ePDx/r0u5BqaDMn2wtxipeOapKuKIR9cPHjaXikqup",
	"coG3jI11DWQevH4EDt6OdW/bLzg/cO+Be58m93ZWfrpxRdFbffUf49vJCBvRE0efsxYbB3PqrzWnvhil",
	"5QgvU07HS5grJf+FjtcIhBGF+8bWS0rBjtrUB9dMrFQI15Yar7OluWw8LYJ/YOGiXXpkrxBl4umVly+t",
	"slLctqMqq53hphbjQeXsS+Wc73uerAPhV6py9ivCjz7XLqO7fMi7kzgvq43AcHud03W9dYndbTuljOsn",
	"9J1N7sYowCLApv9lHnTT/YJIFNn+Jtq0NEOHlbBPVXSY5ewqPF7UIOBtw/4btuALAkhknaUOYuJgme7P",
	"Mj1YZn8Ly2z1V3UJXzPrUodV916fvbnkfLuIbxp2qXwU0fzX2nkHQX8Q9N+ePbhmLPAr8kH362ju4GE6",
	"DtR3ED+OCzEPkuXgaT5hyZK7mGv5loXJsW93L2OYg4N30PvfoIP35NT12o7JBh7JMumwg7tREw1PQM0f",
	"pM1B2nzjtoA2Zc1tKDskIrwEWQiFZ6ISjKrftLJxHsJqefFzsYe95CoU4x14+cDLX33Swh7tgh0lkM1u",
	"bw93ZDUJwVca9rirrn9P4Y8PNbBtbR59aK0u2MFKai9ZOMjOQ0zkCdpBNSm0cWhkJZNvGSKpsfkhUnKw",
	"d77dSMmT1fSPFDFZbRmkcr8S4+lYCAdZdJBFfw/7YWk4ZZnIWxJWqUmORw+vtAmVQ5TlwOmHKMvTirK0",
	"NxDSt7/ruMSURBI4hPWWQvmdRbpFYEimOs1P5uJJLhIQvQl9bzuL/pGaSmi7TiRZfjsEEH2hSN7L7Lv8",
	"wvwPv5prSCc0b4tounZ8jxjPRdt35no2Kxi+L/cvLPU/WlLKilGgZCCEWQuO0mcbS8Q3Fqi7F2av1/7p",
	"IP72I/4Ocsn1adEJbScRc/TZtie6fDhqvVSlZJjYS2TWqmEVutKgYtXk/G/nKro96hv65lggrEWcvaB6",
	"WyZ/Yzf1o93So/O83c+B5w8mzzciWna0XcqCpa3TcUk0mB7MO4uVcsfkx5MqV2Y/jy5UzG4OMuUgU/7m",
	"MmWnA+blPTZqYZj99tpwnfBuKjFae9Yd5MJBLhw6b1QEyfCo9R6erIGd33aH/pLucTLl1JYuVr6uX66f",
	"X7/fuGN/QiWJoWNa9Kk3bN98HUR5cYVmpvU9U0PryMsnHMhoge7nJJjn194TMaEhJBFbmBvBnPJoaFs1",
	"f4EGdFbK2gn/IjHxlPlKpHGM+cLG/BWFZOjLuxfe5diSeKa4Lbsxyvtou/VVO1Pao46Hh/8NAAD//8gy",
	"6Oxm8wAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/v1.17.1/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/region/main/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
