apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-cluster-controller
  template:
    metadata:
      labels:
        app: unikorn-cluster-controller
    spec:
      containers:
      - name: unikorn-cluster-controller
        image: {{ include "unikorn.clusterControllerImage" . }}
        args:
        {{- include "unikorn.core.flags" . | nindent 8 }}
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        {{- include "unikorn.region.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        {{- include "unikorn.mtls.flags" . | nindent 8 }}
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          {{- .Values.clusterController.resources | toYaml | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: {{ .Release.Name }}-cluster-controller
      securityContext:
        runAsNonRoot: true
