apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unikorn-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: unikorn-cluster-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unikorn-cluster-controller
