apiVersion: v1
kind: Service
metadata:
  name: unikorn-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  selector:
    app: unikorn-cluster-controller
  ports:
  - name: prometheus
    port: 8080
    targetPort: prometheus
