apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-virtualcluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-virtualcluster-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-virtualcluster-controller
    spec:
      containers:
      - name: {{ .Release.Name }}-virtualcluster-controller
        image: {{ include "unikorn.virtualClusterControllerImage" . }}
        args:
        {{- include "unikorn.core.flags" . | nindent 8 }}
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        {{- include "unikorn.region.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        {{- include "unikorn.mtls.flags" . | nindent 8 }}
        {{ with $domain := .Values.virtualClusterController.virtualKubernetesClusterDomain -}}
        - --virtual-kubernetes-cluster-domain={{ $domain }}
        {{- end }}
        {{ with $label := .Values.virtualClusterController.nodeSelectorLabel }}
        - --node-selector-label={{ $label }}
        {{- end }}
        {{ if .Values.virtualClusterController.nodeSelectorLabelIsPrefix -}}
        - --node-selector-label-is-prefix
        {{- end }}
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          {{- .Values.virtualClusterController.resources | toYaml | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: {{ .Release.Name }}-virtualcluster-controller
      securityContext:
        runAsNonRoot: true
