apiVersion: unikorn-cloud.org/v1alpha1
kind: KubernetesClusterApplicationBundle
metadata:
  name: kubernetes-cluster-1.0.0
spec:
  version: 1.0.0
  applications:
  - name: cluster-openstack
    reference:
      kind: HelmApplication
      name: cluster-openstack
      version: v0.3.27
  - name: cilium
    reference:
      kind: HelmApplication
      name: cilium
      version: 1.14.1
  - name: openstack-cloud-provider
    reference:
      kind: HelmApplication
      name: openstack-cloud-provider
      version: 2.28.0
  - name: openstack-plugin-cinder-csi
    reference:
      kind: HelmApplication
      name: openstack-plugin-cinder-csi
      version: 2.28.0
  - name: metrics-server
    reference:
      kind: HelmApplication
      name: metrics-server
      version: 3.11.0
  - name: nvidia-gpu-operator
    reference:
      kind: HelmApplication
      name: nvidia-gpu-operator
      version: v23.9.1
  - name: cluster-autoscaler
    reference:
      kind: HelmApplication
      name: cluster-autoscaler
      version: 9.29.3
  - name: cluster-autoscaler-openstack
    reference:
      kind: HelmApplication
      name: cluster-autoscaler-openstack
      version: v0.1.0

