{{- range $region := .Values.regions }}
apiVersion: unikorn-cloud.org/v1alpha1
kind: Region
metadata:
  name: {{ $region.name }}
  labels:
    {{- include "unikorn.labels" $ | nindent 4 }}
spec:
  provider: {{ $region.provider }}
  {{- with $openstack := $region.openstack }}
  openstack:
    endpoint: {{ $openstack.endpoint }}
    serviceAccountSecret:
      namespace: {{ $openstack.serviceAccountSecret.namespace }}
      name: {{ $openstack.serviceAccountSecret.name }}
    {{- with $identity := $openstack.identity }}
      {{ printf "identity:" | nindent 4 }}
      {{- with $roles := $identity.clusterRoles }}
        {{ printf "clusterRoles:" | nindent 6 }}
        {{- range $role := $roles }}
          {{ printf "- %s" $role | nindent 6 }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with $compute := $openstack.compute }}
      {{ printf "compute:" | nindent 4 }}
      {{- with $policy := $compute.serverGroupPolicy }}
        {{ printf "serverGroupPolicy: %s" $policy | nindent 6 }}
      {{- end }}
      {{- with $specs := $compute.flavorExtraSpecsExclude }}
        {{ printf "flavorExtraSpecsExclude:" | nindent 6 }}
        {{- range $spec := $specs }}
          {{ printf "- %s" $spec | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- with $descriptors := $compute.gpuDescriptors }}
        {{ printf "gpuDescriptors:" | nindent 6 }}
        {{- range $descriptor := $descriptors }}
          {{ printf "- property: %s" $descriptor.property | nindent 6 }}
          {{ printf "expresison: %s" $descriptor.property | nindent 8 }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with $image := $openstack.image}}
      {{ printf "image:" | nindent 4 }}
      {{- with $properties := $image.propertiesInclude }}
        {{ printf "propertiesInclude:" | nindent 6 }}
        {{- range $property := $properties }}
          {{ printf "- %s" $property | nindent 6 }}
        {{- end }}
      {{- end }}
      {{- with $signingKey := $image.signingKey }}
        {{ printf "signingKey: %s" $signingKey | nindent 6 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
