apiVersion: v1
kind: ServiceAccount
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
{{- with ( include "unikorn.imagePullSecrets" . ) }}
imagePullSecrets:
{{ . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage control planes (my job).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - clustermanagers
  verbs:
  - list
  - get
  - watch
  - update
  - patch
- apiGroups:
  - unikorn-cloud.org
  resources:
  - clustermanagers/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
# Manage clusters (cascading deletion).
- apiGroups:
  - unikorn-cloud.org
  resources:
  - kubernetesclusters
  verbs:
  - list
  - get
  - watch
  - delete
# Get application bundles
- apiGroups:
  - unikorn-cloud.org
  resources:
  - helmapplications
  - clustermanagerapplicationbundles
  verbs:
  - list
  - watch
# ArgoCD integration.
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - list
  - get
  - watch
  - patch
  - delete
# ArgoCD integration (access to API secret).
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - create
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Controller prerequisites.
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: unikorn-cluster-manager-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unikorn-cluster-manager-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: unikorn-cluster-manager-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unikorn-cluster-manager-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-cluster-manager-controller
  template:
    metadata:
      labels:
        app: unikorn-cluster-manager-controller
    spec:
      containers:
      - name: unikorn-cluster-manager-controller
        image: {{ include "unikorn.clusterManagerControllerImage" . }}
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-cluster-manager-controller
      securityContext:
        runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
    {{- include "unikorn.prometheusLabels" (dict "job" "unikorn-cluster-manager-controller") | nindent 4 }}
spec:
  selector:
    app: unikorn-cluster-manager-controller
  ports:
  - name: prometheus
    port: 8080
    targetPort: prometheus
