apiVersion: apps/v1
kind: Deployment
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unikorn-cluster-manager-controller
  template:
    metadata:
      labels:
        app: unikorn-cluster-manager-controller
    spec:
      containers:
      - name: unikorn-cluster-manager-controller
        image: {{ include "unikorn.clusterManagerControllerImage" . }}
        args:
        {{- include "unikorn.core.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: unikorn-cluster-manager-controller
      securityContext:
        runAsNonRoot: true
