apiVersion: v1
kind: Service
metadata:
  name: unikorn-cluster-manager-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
    {{- include "unikorn.prometheusLabels" (dict "job" "unikorn-cluster-manager-controller") | nindent 4 }}
spec:
  selector:
    app: unikorn-cluster-manager-controller
  ports:
  - name: prometheus
    port: 8080
    targetPort: prometheus
